[package]
name = "quickraw"
version = "0.1.1"
edition = "2021"

[dependencies]
attrs = {path="attrs"}
anyhow = "1"
image = "0.23"
thiserror = "1.0"
phf = {version = "0.10", features = ["macros"]}
rayon = "1.5"

[profile.release]
codegen-units = 1
lto="fat"
